#!/usr/bin/env bash
# Configures localhost and facebook.com IP addresses in /etc/hosts

sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts
sudo sed -i 's/.*facebook.com/8.8.8.8 facebook.com/' /etc/hosts
